### PR TITLE
Fixed #7 (really hacky, definitely is WIP)

### LINKED ISSUE #7: The names of the `PackageGuids` and `PackageIds` classes that are generated should be user-configurable
Hi @madskristensen I am working on Issue #59 of the madskristensen\ExtensionPackTools repository and I am running into the need to customize the `PackageGuids` and `PackageIds` classes that are auto-generated (as well as their access modifiers) by this tool.

Can i go ahead and make the change here and then open a PR to address this issue?

Basically, the **Access Modifier** (which defaults to `internal`) property and the `PackageGuidsClassName` and `PackageIdsClassName` properties will now be in the Visual Studio **Properties** window when someone clicks a `.vsct` file in the **Solution Explorer** window.

As part of my work, I am adhering to the convention of always naming the root namespaces after the containing project.  This is causing collisions between auto-generated `PackageGuids` etc. classes of the same name in the code-behinds of the `.vsct` files in the respective `ExtensionManager2017`, `ExtensionManager2019` and `ExtensionManager2022` projects.

### PR DESCRIPTION
**Pull request by astrohart**
Need to differentiate the name of the `PackageGuids` and `PackageIds` classes that are generated by this extension through the process of generating them.  Included the `{FileNamespace}` in the name of the class; if the file's namespace is `Foo`, then the classes will now be named `FooPackageGuids` and `FooPackageIds` which is necessary to avoid name collisions in big solutions.

### CODE REVIEW

**Comment by madskristensen** [comment]
What's the purpose of making it `public` over `internal`? The VSIX project is unlikely to be consumed by other external code

**Comment by madskristensen** [comment]
Why sign the extension and why add an .ico file?

**Comment by madskristensen** [comment]
Why add the application icon in the csproj file

**Comment by astrohart** [comment]
> Why sign the extension and why add an .ico file?

You know, I can't provide a good answer for that.  That change can be backed out, I thought it was necessary.

**Comment by astrohart** [comment]
> What's the purpose of making it `public` over `internal`? The VSIX project is unlikely to be consumed by other external code

So in `ExtensionPackTools`, there is a shared items project, along with three VSIX projects in that solution, one for each supported version of VS.

If you remember per our discussion in regards to best practices.  Well, one best practice I always like to do is to synchronize my namespaces with the project name and folder the file is in.

So, I ran that in ReSharper.  And now the code is broken because (formerly) `internal` classes `Vsix`, `PackageGuids`, and `PackageIds` are referenced by the shared-item project because now these classes are declared in a, e.g., `ExtensionManager2017` namespace but they are referenced by code in the `ExtensionManager.Shared` namespace (what I renamed the namespace of the shared-items project to).  They could be referenced before because all projects shared the same name space (I know why you did it that way, as a time-saver, but it's not a good idea in my mind because you risk referential degeneracy, meaning it's only clear to the compiler, but not the human code-maintainer, which class is being referenced from where, and that reduces maintainability).  If these classes are `public` then we do not have this problem.  And I really do not see any issue with making them `public`, I mean, they contain information that has to be referenced everywhere it's needed through the software system, so why not make them `public`?

**Comment by astrohart** [comment]
I wish to withdraw this PR entirely.

**Pull request closed without merging**
